lena=imread('lena.bmp');
R = lena (:,:, 1), G = lena (:,:, 2), B = lena (:,:, 3);
figure (1);
subplot (2,2,1), imshow (lena), title ('Original');
subplot (2,2,2), imshow (R), title ('R');
subplot (2,2,3), imshow (G), title ('G');
subplot (2,2,4), imshow (B), title ('B');
ima=rgb2hsv(lena);
h = ima (:,:, 1), s = ima (:,:, 2), v = ima (:,:, 3);
figure (2);
subplot (2,2,1), imshow (ima), title ('Original');
subplot (2,2,2), imshow (h), title ('h');
subplot (2,2,3), imshow (s), title ('s');
subplot (2,2,4), imshow (v), title ('v');
ima=rgb2ycbcr(lena);
y = ima (:,:, 1), cb = ima (:,:, 2), cr = ima (:,:, 3);
figure (3);
subplot (2,2,1), imshow (ima), title ('Original');
subplot (2,2,2), imshow (y), title ('y');
subplot (2,2,3), imshow (cb), title ('cb');
subplot (2,2,4), imshow (cr), title ('cr');
ima=rgb2lab(lena);
l = ima (:,:, 1), a = ima (:,:, 2), b = ima (:,:, 3);
figure (4);
subplot (2,2,1), imshow (ima), title ('Original');
subplot (2,2,2), imshow (l,[]), title ('l');
subplot (2,2,3), imshow (a,[]), title ('a');
subplot (2,2,4), imshow (b,[]), title ('b');

